// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5I2JJmuc5xKsHrV5ZcVAQKMuDufMezJ4',
    appId: '1:1067121560615:web:e5bd136690d8661dac5202',
    messagingSenderId: '1067121560615',
    projectId: 'pozy-ec935',
    authDomain: 'pozy-ec935.firebaseapp.com',
    storageBucket: 'pozy-ec935.firebasestorage.app',
    measurementId: 'G-QGB530K1RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIaXv92j6Pwt0hwVOEo5Xynqnnh0zRRGs',
    appId: '1:1067121560615:android:d1e43d6be665c308ac5202',
    messagingSenderId: '1067121560615',
    projectId: 'pozy-ec935',
    storageBucket: 'pozy-ec935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk4EzijJW6WEasBA3VUBT2gJTLlcWNH5Y',
    appId: '1:1067121560615:ios:4546c2ee5f84f5a5ac5202',
    messagingSenderId: '1067121560615',
    projectId: 'pozy-ec935',
    storageBucket: 'pozy-ec935.firebasestorage.app',
    iosBundleId: 'com.example.poseCameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk4EzijJW6WEasBA3VUBT2gJTLlcWNH5Y',
    appId: '1:1067121560615:ios:4546c2ee5f84f5a5ac5202',
    messagingSenderId: '1067121560615',
    projectId: 'pozy-ec935',
    storageBucket: 'pozy-ec935.firebasestorage.app',
    iosBundleId: 'com.example.poseCameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5I2JJmuc5xKsHrV5ZcVAQKMuDufMezJ4',
    appId: '1:1067121560615:web:f6f77a5b411955e1ac5202',
    messagingSenderId: '1067121560615',
    projectId: 'pozy-ec935',
    authDomain: 'pozy-ec935.firebaseapp.com',
    storageBucket: 'pozy-ec935.firebasestorage.app',
    measurementId: 'G-3VQZB6Y6KT',
  );
}
